// <auto-generated />
using Beca.PlaylistInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beca.PlaylistInfo.API.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20221104085038_DataSeed3")]
    partial class DataSeed3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("Canciones");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Descripcion = "cancion buenisima",
                            Nombre = "in the end",
                            PlaylistId = 2
                        });
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Descripcion = "linking park lista",
                            Nombre = "linkin park"
                        });
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Cancion", b =>
                {
                    b.HasOne("Beca.PlaylistInfo.API.Entities.Playlist", "Playlist")
                        .WithMany("Canciones")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("Beca.PlaylistInfo.API.Entities.Playlist", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
